name: CI latest

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-image:
    name: Build and publish image
    runs-on: ubuntu-latest

    steps:

      - name: 'Github: checkout'
        uses: actions/checkout@v3

      - name: 'Github: setup Node.js LTS'
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 'Angular: install'
        run: npm install

      - name: 'Angular: run tests'
        run: npm run test:prod

      - name: 'Angular: build'
        run: npm run build:prod

      - name: 'Dockerhub: login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Dockerhub: build and push'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
